services:
  ha-api:
    container_name: ha-api
    build: 
      context: /opt//ha-api
      dockerfile: Dockerfile
    volumes:
      - /opt/google.json:/app/google.json:ro
    restart: unless-stopped
    ports:
      - "5000:5000" 
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

